import Head from "next/head";
import React from "react";
import { useEffect, useState } from "react";
import ListingCard from "../components/Cards/ListingCard";
import axiosInstance from "../helpers/axios";
import ShelterCard from "../components/Cards/ShelterCard";
import IndexBanner from "../components/Banners/IndexBanner";
import NavButton from "../components/Buttons/NavButton";

export default function Home() {
  const [listings, setListings] = useState([]);
  const [shelters, setShelters] = useState([]);

  useEffect(() => {
    const token = window.localStorage.getItem("token");
    axiosInstance.defaults.headers.Authorization = `Bearer ${token}`;

    const fetchListings = async () => {
      const { data } = await axiosInstance.get("/api/animals/dogs");
      //Slice to Limit only 8 in index
      setListings(data.data.slice(0, 8));
    };

    const fetchShelters = async () => {
      const { data } = await axiosInstance.get("/api/get_shelters");
      setShelters(data.data.slice(0, 8));
    };

    fetchListings();
    fetchShelters();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Adopt dog</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-40"></div>
      <IndexBanner />
      {/* Listings */}
      <main className="px-8 mx-auto max-w-7xl sm:px-16">
        <section className="pt-6">
          <h3 className="pb-5 text-4xl font-semibold">Adopt Me</h3>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {listings.map((item) => (
              <div className="mb-10 overflow-hidden rounded-2xl">
                <ListingCard
                  key={item.id}
                  name={item.name}
                  image={item.cover_image}
                  title={item.title}
                  age={item.age}
                  city={item.city}
                  id={item.id}
                />
              </div>
            ))}
          </div>
          <div className="flex justify-center mx-auto">
            <NavButton title="See more" link="/listings/animals" />
          </div>
        </section>
        {/* Shelter section*/}
        <section className="pt-6">
          <h3 className="pb-5 text-4xl font-semibold">Find Shelter</h3>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {shelters.map((item) => (
              <div className="mb-10 overflow-hidden rounded-2xl">
                <ShelterCard
                  key={item.id}
                  name={item.shelter_name}
                  image={item.cover_image}
                  city={item.city}
                />
              </div>
            ))}
          </div>
          <div className="flex justify-center mx-auto ">
            <NavButton title="See more" link="/listings/shelters" />
          </div>
        </section>
      </main>
    </div>
  );
}
