import Head from "next/head";
import React from "react";
import { useEffect, useState, useContext } from "react";
import ListingCard from "../components/Cards/ListingCard";
import axiosInstance from "../helpers/axios";
import IndexBanner from "../components/Banners/IndexBanner";
import NavButton from "../components/Buttons/NavButton";
import NoResults from "../components/CustomImages/Illustrations/NoResults";
import { Context } from "../context";
import ListingsRowSection from "../components/Sections/IndexPage/ListingsRowSection";
import axios from "axios";
import GeneralStatsCard from "../components/Cards/GeneralStatsCard";

export default function Home() {
  const [listings, setListings] = useState([]);
  const [shelters, setShelters] = useState([]);
  const [lostListings, setLostlistings] = useState([]);
  const [foundListings, setFoundListings] = useState([]);
  const [generalStats, setGeneralStats] = useState([]);

  const { state, dispatch } = useContext(Context);
  const [token, setToken] = useState("");
  const { user } = state;

  useEffect(() => {
    const localItemToken = window.localStorage.getItem("token");
    if (localItemToken) {
      setToken(localItemToken);
      axiosInstance.defaults.headers.Authorization = `Bearer ${window.localStorage.getItem(
        "token"
      )}`;
    }

    fetchListings();
    fetchShelters();
    fetchLostListings();
    fetchFoundListings();
    fetchGeneralStats();
  }, []);

  const fetchListings = async () => {
    const { data } = await axiosInstance.get("/api/animals/dogs");
    //Slice to Limit only 8 in index
    setListings(data.data.slice(0, 8));
  };

  const fetchShelters = async () => {
    const { data } = await axiosInstance.get("/api/get_shelters");
    setShelters(data.data.slice(0, 8));
  };

  const fetchLostListings = async () => {
    const { data } = await axiosInstance.get(
      "/api/animals/lost-dogs/all?sortBy=lost_at"
    );
    setLostlistings(data.data.slice(0, 8));
  };

  const fetchFoundListings = async () => {
    const { data } = await axiosInstance.get(
      "/api/animals/found-dogs/all?sortBy=found_at"
    );
    setFoundListings(data.data.slice(0, 8));
  };

  const fetchGeneralStats = async () => {
    const { data } = await axiosInstance.get("/api/get_stats");
    setGeneralStats(data.data);
  };

  return (
    <>
      <Head>
        <title>Goodboi Heros</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>
      <div className="pt-20"></div>
      <IndexBanner user={user} />

      <main className="p-4 lg:p-16 ">
        {/* Stats*/}
        <section className="lg:p-6">
          <div className="mx-auto max-w-s ">
            <div className="grid gap-5 sm:grid-cols-4">
              {generalStats.length != 0 &&
                generalStats.map((item) => (
                  <GeneralStatsCard
                    key={item.name}
                    title={item.name}
                    count={item.count}
                  />
                ))}
            </div>
          </div>
        </section>
        {/* Dogs for adoption */}
        <section className="lg:p-6">
          <h3 className="pb-5 header_titles">Adopt Me</h3>
          {listings.length === 0 ? (
            <div className="flex justify-center w-full pt-20 pb-20">
              <NoResults />
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {listings.map((item) => (
                <div
                  key={item.id}
                  className="mb-10 overflow-hidden rounded-2xl"
                >
                  <ListingCard
                    item={item}
                    token={token}
                    isfavourite={item.is_favourited}
                  />
                </div>
              ))}
            </div>
          )}

          <div className="flex justify-center mx-auto">
            <NavButton title="See more" link="/listings/animals" />
          </div>
        </section>

        {/* Lost dogs section*/}
        <ListingsRowSection
          key={1}
          title="Lost Dogs"
          listings={lostListings}
          listingType="lost"
          buttonUrl="/listings/lost-dogs"
        />
        {/* Found dogs section*/}
        <ListingsRowSection
          key={2}
          title="Found Dogs"
          listings={foundListings}
          listingType="found"
          buttonUrl="/listings/found-dogs"
        />
        {/* Shelter section*/}
        <ListingsRowSection
          key={3}
          title="Shelters"
          listings={shelters}
          listingType="shelters"
          buttonUrl="/listings/shelters"
        />
      </main>
    </>
  );
}
